// AUTO-GENERATED by scripts/fetch-holidays.mjs — DO NOT EDIT
// Refresh explicitly with: npm run fetch:holidays (not a build hook).

import type { HolidayYear } from '../../utils/holiday';

import y2026 from './2026.json';
import y2027 from './2027.json';

export const ALL_HOLIDAYS: HolidayYear[] = [y2026, y2027];
